language: node_js
node_js: 10
matrix:
    include:
        - os: linux
          dist: trusty
        - os: osx
          osx_image: xcode8.3
env:
    global:
        - GITHUB_REPO: fincubator/dex-ui
        - ORGANIZATION_REPO: finteh/finteh.org
        - WALLET_REPO: fincubator/dex.finteh.org
        - CXX=g++-4.8
        - secure:
              JCZrhZV2VQEhh1PnY5QJO1hlgty3LXaeo4N9W0f6pBs78qNFT5mir2B7bH2WaIE/v9aP8PNJF8eCGYPMm1VKBlNtVkGOCXpOJlGXzFhKQ6jlxZD/VD8PF3vgpeMWgiGg8fPSKNjreZnhXyRZ/TBgwsbIkZYFKLhwVlRv0LJsjs69xPw+/BFiAtpdHdoN5XjZ+rycaP0W756sjcdce+6nZ+kyKVhHuCUGm0Q0WAyzvn0oztacQOfB/QB2T+v7QSVG9s361HddC+Zg4PDhAeLBhWRn9SiDyuWqYXtbir2k9i+IRu2TFXThi1gTD6OFIdTxqRbKwWHtcuW8svVvrYXNvwJEidoKQYRoAjuvMz8MlhkaeDsQBvMS7q8b2fhKItIZdpp3rZ2/08fNGfg3oiwGbAYl9ES60cGDWLxDu7hhT6JN4+FCSyG+kfbtR2rmOl2mytVKHKBLwDkw6k0vGv4CLr0IMJ5Pf7wwxaj5v3n6o/NJdBKt/Q7SmEIYwdwp4chC0qidP4MSeepTDSf3/y/VXB9oz+kUKtXOHA4qYnAZDVIjRXLYKv9giK1QlOYEM6nfVYsn0TieMdtNu8fBQPOj+DFX1KY/3bCZXO04fbs0slHWwPNNE/ZPlWalhTT/0o1+QDqZaulSoqEVoqTaRuSLoQe/WAZuSfy947rmjhE0oo0=
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.8
            - g++-4.8
            - icnsutils
            - graphicsmagick
            - xz-utils
install:
    - npm ci
script:
    - "./build.sh"
after_success: "./deploy.sh"
deploy:
    provider: releases
    tag_name: $TRAVIS_TAG
    name: $TRAVIS_TAG
    body: Automated release from Travis CI with added files from AppVeyor build
    api_key:
        secure:
            JCZrhZV2VQEhh1PnY5QJO1hlgty3LXaeo4N9W0f6pBs78qNFT5mir2B7bH2WaIE/v9aP8PNJF8eCGYPMm1VKBlNtVkGOCXpOJlGXzFhKQ6jlxZD/VD8PF3vgpeMWgiGg8fPSKNjreZnhXyRZ/TBgwsbIkZYFKLhwVlRv0LJsjs69xPw+/BFiAtpdHdoN5XjZ+rycaP0W756sjcdce+6nZ+kyKVhHuCUGm0Q0WAyzvn0oztacQOfB/QB2T+v7QSVG9s361HddC+Zg4PDhAeLBhWRn9SiDyuWqYXtbir2k9i+IRu2TFXThi1gTD6OFIdTxqRbKwWHtcuW8svVvrYXNvwJEidoKQYRoAjuvMz8MlhkaeDsQBvMS7q8b2fhKItIZdpp3rZ2/08fNGfg3oiwGbAYl9ES60cGDWLxDu7hhT6JN4+FCSyG+kfbtR2rmOl2mytVKHKBLwDkw6k0vGv4CLr0IMJ5Pf7wwxaj5v3n6o/NJdBKt/Q7SmEIYwdwp4chC0qidP4MSeepTDSf3/y/VXB9oz+kUKtXOHA4qYnAZDVIjRXLYKv9giK1QlOYEM6nfVYsn0TieMdtNu8fBQPOj+DFX1KY/3bCZXO04fbs0slHWwPNNE/ZPlWalhTT/0o1+QDqZaulSoqEVoqTaRuSLoQe/WAZuSfy947rmjhE0oo0=
    file_glob: true
    file:
        - build/binaries/finteh*
        - build/release-checksums-*
    skip_cleanup: true
    draft: true
    on:
        repo: finteh/dex-ui
        tags: true
