version: 1.0.{build}
environment:
    nodejs_version: 10
install:
    # Get the latest stable version of Node.js or io.js
    - ps: Install-Product node $env:nodejs_version
    # install modules
    - npm ci
build: off
platform:
    - x64
before_package: echo Before package
after_test:
    - 7z a build\html5_history_dist_%APPVEYOR_REPO_TAG_NAME%.zip %APPVEYOR_BUILD_FOLDER%\build\dist -r
    - 7z a build\hash_history_dist_%APPVEYOR_REPO_TAG_NAME%.zip %APPVEYOR_BUILD_FOLDER%\build\hash-history -r
    - node ./write_digest.js
test_script:
    - npm run package
    - npm run build
    - npm run build-hash
artifacts:
    - path: build\binaries\*.exe
      name: WindowsApp
    - path: build\html5_history_dist_*.zip
      name: html5_history_dist
    - path: build\hash_history_dist_*.zip
      name: hash_history_dist
    - path: build\release-checksums-*
      name: release-checksums-windows
deploy:
    provider: GitHub
    release: $(APPVEYOR_REPO_TAG_NAME)
    description: "Automated release from Travis CI with added files from AppVeyor build"
    auth_token:
        secure: aD/kZvtVYdQsu3os0E43afwsIVfn/sQCKC2n+B21T2h+LxXGcCYx6K7YiqF9L5nk
    artifact: WindowsApp, html5_history_dist, hash_history_dist, release-checksums-windows
    draft: true
    force_update: true
    on:
        appveyor_repo_tag: true
